name: Build and Push Docker Image

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: steady-tracer-392814
  REGION: europe-west3
  REGISTRY_NAME: europe-west3-docker.pkg.dev/steady-tracer-392814/iot
  IMAGE_NAME: appjs
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: |
          gcloud auth configure-docker "${env.REGISTRY_NAME}"

      - name: Build and Push Docker image
        run: |
          docker build -t "${env.REGISTRY_NAME}/${env.IMAGE_NAME}:${env.IMAGE_TAG}" .
          docker push "${env.REGISTRY_NAME}/${env.IMAGE_NAME}:${env.IMAGE_TAG}"
